import type { Metadata } from "next";

import "./globals.css";
import "@copilotkit/react-ui/styles.css";
import { FakeAuthProvider } from "./components/fake-auth-provider"
import { UserMenu } from "./components/user-menu"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"antialiased"}>
        <FakeAuthProvider>
          {children}
          <UserMenu />
        </FakeAuthProvider>
      </body>
    </html>
  );
}
